[theme]
primaryColor = "#FEC868"
backgroundColor = "#F5F8EE"
secondaryBackgroundColor = "#ECF1E2"
textColor = "#242B18"
font = "sans serif"

[ui]
sidebarNavVisibility = "visible"

[browser]
gatherUsageStats = false
